### ISSUE TITLE
Stage(s) always destroyed regardless of parachutes.

### ISSUE THREAD

**Issue by macrosblackd** [magico13/StageRecovery#13]
I've got 4 of these:
```
1x FL-T100 Fuel Tank
1x J-33 "Wheesley" Basic Jet Engine
1x Aerodynamic Nose Cone
1x Mk2-R Radial-Mount Parachute
```
I've tried a dozen flights and can't get these to recover. Each of these stages is ~$2500 and not being able to recover them would be disastrous. I always get a message saying they've been destroyed at 108m/s velocity. I've also set the DR Velocity to a really high value in case that was what was causing it.

**Comment by magico13** [comment]
Have you updated to SR 1.5.5 for 1.0.2? That update should fix this issue

**Comment by macrosblackd** [comment]
Sorry, just saw there was an update - I had only JUST grabbed the mod
this morning too =D

Giving it a test, will report back.

**Comment by macrosblackd** [comment]
Stages recovered successfully! Yay!

**Comment by Barhandar** [comment]
Getting that, with reported velocity around 35 m/s, on 1.5.5, regardless if chute was activated or not (no success message and no debris visible afterwards if have personally watched the parachute descent up close - but unopened parachute failed to deploy and resulted in failure). Using FAR, which seems to include RealChutesLite - maybe an incompatibility?

**Comment by magico13** [comment]
> Using FAR, which seems to include RealChutesLite - maybe an incompatibility?

RealChute Lite is currently unsupported. You either need to install full RealChutes or uninstall FAR, or just not have recoveries. I plan on adding support some time this weekend.
