### ISSUE TITLE
Incorrect calculation of distance for stage recovery

### ISSUE THREAD

**Issue by burbel** [magico13/StageRecovery#16]
Have had this happen multiple times on a completely fresh save.  Whether I try and turn to enter orbit or launch straight up from KSC (still early in career) the distance for the recovered stages states "Stage recovered 942.48km from...".  This even happens for a stage that is left on the landing pad.  I've tried searching through output.txt and can't see any output from stagerecovery - happy to gather more data if it'd be helpful.

The 942.48km is consistent, even with stages that in theory drop a few km from KSC.

**Comment by magico13** [comment]
Is this with 1.5.6 and do you have Kerbal Konstructs (or KerbinSide or anything else that uses Kerbal Konstructs) or KSCSwitcher installed?

Log files are always appreciated. 1.5.6 logs the lat/lon of both the stage and KSC to help debug issues like these. It also included a change to the determination of a stage's latitude and longitude (which increased accuracy in my tests for at least one case that gave wrong reports before)

**Comment by burbel** [comment]
I found going through all the mods that I had a Kopernicus mod installed - your mod gives me 2 digits after the decimal so my early googling failed, but checking on a post-mission status I noticed with one digit I was able to match a google search for http://forum.kerbalspaceprogram.com/threads/109512-Recovery-values-for-Parts-incorrect-(Kopernicus-).

It seems to be working with that mod removed (not sure what included it, I haven't tried any alternate KSC mods nor extra planets, but sometimes CKAN brings items in that you don't expect).

I checked in output.txt, what output string do you use for your logging latitude/longitude?  Will go back and search just for edification.

**Comment by magico13** [comment]
Ah, forgot about Kopernicus. Others have reported the same issue with that installed. Someone mentioned on the SR thread in the forums that the Kopernicus devs are working on a fix for that, but I don't know anything about it.

While SR attempts to recover something it should list the latitude and longitude of the vessel, then KSC, and then the distance, starting with this text: "[SR] Vessel Lat/Lon:".

You can manually override the distance percentage in the SR settings file (Config.txt in the StageRecovery folder) to get around the issue if you want. I'd suggest something like 0.95 (so, 95%).

**Comment by burbel** [comment]
I've got Kopernicus removed now so no worries, but good to know about a workaround.  You might want to make a mention on the first post on the forums if people are searching for answers/known issues.  

Sorry for the errant bug report.  Wish that the KSP output.txt file had timestamps, but my most recent logged value (with it working) reported:

[SR] Vessel Lat/Lon: -0.151821317088561/286.464116839215
[SR] KSC Lat/Lon: -0.0917535887291978/285.370305309136
[SR] Distance: 4269.618

Thanks for the quick responses and the amazingly helpful mod!
