### ISSUE TITLE
Incomplete AVC file causes CKAN grief

### ISSUE THREAD

**Issue by hakan42** [magico13/StageRecovery#2]
CKAN tries to expand version information from the .version file. It stumbles over the one-item version string in your package.

Could you, by any chance, change your version file to look like (also, please make sure that it is valid JSON, verifying especially the comma signs...

```
     "VERSION":{
         "MAJOR":1,
         "MINOR":5,
         "PATCH":3,
         "BUILD":4711
     },
     "KSP_VERSION":{
         "MAJOR":0,
         "MINOR":90,
         "PATCH":0
     },
     "KSP_VERSION_MIN":{
         "MAJOR":0,
         "MINOR":90,
         "PATCH":0
     },
     "KSP_VERSION_MAX":{
         "MAJOR":0,
         "MINOR":90,
         "PATCH":0
     }
```

**Comment by magico13** [comment]
I know this was a while ago and I think CKAN can actually handle this now, but in the last version of StageRecovery I tried to fix up the version file so it followed this syntax instead. I'm going to close this now, but feel free to let me know if the issue still persists.
