### ISSUE TITLE
Kerbals die/go MIA from landed craft when switching focus. 

### ISSUE THREAD

**Issue by se5a** [magico13/StageRecovery#28]
see this thread: http://forum.kerbalspaceprogram.com/index.php?/topic/129786-valentina-died-sitting-in-her-landed-vehicle-stagerecovery/#comment-2380661

To quote Tfin:
To follow up, I just went back to the limited-mod install, with ONLY Stage Recovery installed. The same thing happens.

Launched new aircraft.
Set the brakes, leaving it parked on the runway.
Used map to switch to craft landed on Mun.
Occupants of lander are OK.
Used map to switch back to plane.
Occupant is dead.
So, it's back to that. Stage Recovery killed my pilots.

**Comment by se5a** [comment]
I've not tried 1.6.2 I'm currently on 1.6.0. I'll do that.

**Comment by magico13** [comment]
1.6.2 will do the same thing. Revert back to 1.5.8 for the mean time. We were actually just discussing it on the [SR thread here](http://forum.kerbalspaceprogram.com/index.php?/topic/78226-105-stagerecovery-recover-funds-from-dropped-stages-v162-010216/&do=findComment&comment=2380045). I know exactly why it's happening, it's the Kerbal pre-recovery code that I added in 1.6.0 to fix the issue of the Stock game killing Kerbals and SR unkilling them on successful recovery, resulting in lost reputation and failed contracts. 

It's ironic that the feature that saves Kerbals from death is inadvertently killing them. Had I known about it earlier I could have fixed it a while ago, but today was the first time anyone reported it to me. I can't promise a fix tonight, but I should have one within the next few days, until then use 1.5.8.

**Comment by se5a** [comment]
Ah cool. excellent. yeah it took us a while to nail down exactly what was causing it. (I initially dismissed SR due to knowing someone else running SR and not having the problem, I guess he's on an older version)

**Comment by magico13** [comment]
>I guess he's on an older version

Could be, it's also really specific because it will only occur for Kerbals in vessels on Kerbin and only when they're left there during a scene change. I imagine most people don't leave Kerbals landed in vessels very often, they usually leave them in space or have recovered them when they switch away. In all the playing I've done since 1.6 released (probably only 10 hours or so) I hadn't run into that situation myself, and I hadn't thought to test that situation.

**Comment by magico13** [comment]
If you're willing, would you try out [this development build](http://magico13.net:8080/job/StageRecovery%20Development/51/artifact/StageRecovery/obj/Debug/StageRecovery.dll)? The only change is a potential fix for this bug. I just need to know whether it works for you or not. It seemed to fix the problem on my end.

**Comment by se5a** [comment]
Yup that appears to work for me.
