### ISSUE TITLE
Global recovery multiplier for reducing recovered cost in any circumstances

### ISSUE THREAD

**Issue by 8749236** [magico13/StageRecovery#39]
User Story: I want a global refund multiplier, in percentage, that allows me to adjust all refunds from stage recovery so I can balance Stage Recovery's impact on game's economy. 0% = no refunds, 100% = total refunds.

What:
Add an extra option (slider) to Stage Recovery's settings window that adjust a multiplier ranging from 0% - 100%.
Which, given refund, R, from a recovered stage.
Total refund is modified by M.

Example:
Stage is dropped and is recovered by Stage Recovery mod.
Suppose after using Flat Rate or Variable Rate model..
Stage should be refund for 100 funds.
Let M = 50% (M is global refund multiplier)
100 * 0.5 = 50.
The player will only get 50 funds back.

Why:
1. In real world, recovering boosters and transport it back to the factory isn't all parts that consumes money.
Refurbishment also costs money.
By adding this new settings, players can at least pretends that we are refurbishing our boosters.
2. Balance Stage Recovery. Players can simply launch all there rocket by stacking dozen parachutes to get most of their cash back from their first stage boosters; which is the part of the rocket that costs the most in the game.
For example: 
Launch a rocket vertically with an overpowered booster that has 20 parachutes on it, which also costs 1 million funds.
Jettison the stage and make sure its orbit gets close to KSC.
???
Profit! ~50% launch cost is now reduced.

Note:
This multiplier should affects both Flat Rate and Variable Rate model

PS: Can someone add a label for this?

**Comment by magico13** [comment]
Added in StageRecovery 1.6.5 for KSP 1.2
