### ISSUE TITLE
Double UI Buttons + Double Recovery Reward

### ISSUE THREAD

**Issue by Belkon** [magico13/StageRecovery#42]
The newest version of the mod has a game breaking issue where I will get almost double my cash for recovery. It gives me two separate notifications for one item, and they both give back funds.

![20161024182928_1](https://cloud.githubusercontent.com/assets/10257252/19668926/72fa325c-9a18-11e6-93fa-932586d9b824.jpg)
![20161024182933_1](https://cloud.githubusercontent.com/assets/10257252/19668928/7688b9a2-9a18-11e6-9919-e8eea7e7ed5b.jpg)
![20161024182931_1](https://cloud.githubusercontent.com/assets/10257252/19668940/8b3f5054-9a18-11e6-8b86-44cf2a67fc84.jpg)
![20161024182934_1](https://cloud.githubusercontent.com/assets/10257252/19668943/8d8e1a66-9a18-11e6-8579-5ff78ccf3ad4.jpg)

There were only two stages recovered yet I got four notifications and double my funds. The UI also shows that there are only two stages that have been recovered.

![20161024182948_1](https://cloud.githubusercontent.com/assets/10257252/19668961/b60cda9a-9a18-11e6-8ce7-66dc57d2cfee.jpg)
![20161024182950_1](https://cloud.githubusercontent.com/assets/10257252/19668963/b8516208-9a18-11e6-9314-71f71a537c89.jpg)

**Comment by 81ninja** [comment]
How was your rocket designed?

SR doesn't list the recovered stages by _stage_, but by _part/vessel_. If you have a stage that drops say 2 boosters (separated from each other), 2 different "debris" vessels are created, then recovered, and thus 2 buttons.

**Comment by Belkon** [comment]
My rocket had only two boosters attached, as you can see in the stage recovery panel. Yet I get I got 4 notifications.

**Comment by magico13** [comment]
You didn't happen to install the mod twice somehow did you? There should
only be one .DLL in the GameData/StageRecovery folder. The output_log.txt
file from the KSP_Data folder would also help to see.

**Comment by Belkon** [comment]
```
[LOG 18:29:30.252] Load(Assembly): Squad/StageRecovery/StageRecovery
[LOG 18:29:30.253] AssemblyLoader: Loading assembly at E:\Steam\steamapps\common\Kerbal Space Program\GameData\Squad\StageRecovery\StageRecovery.dll
[LOG 18:29:30.290] Load(Assembly): StageRecovery/StageRecovery
[LOG 18:29:30.290] AssemblyLoader: Loading assembly at E:\Steam\steamapps\common\Kerbal Space Program\GameData\StageRecovery\StageRecovery.dll
```

Yup you were right, just an accidental missed drag and drop. Sorry for bothering you.

**Comment by Belkon** [comment]
```
[LOG 18:29:30.252] Load(Assembly): Squad/StageRecovery/StageRecovery
[LOG 18:29:30.253] AssemblyLoader: Loading assembly at E:\Steam\steamapps\common\Kerbal Space Program\GameData\Squad\StageRecovery\StageRecovery.dll
[LOG 18:29:30.290] Load(Assembly): StageRecovery/StageRecovery
[LOG 18:29:30.290] AssemblyLoader: Loading assembly at E:\Steam\steamapps\common\Kerbal Space Program\GameData\StageRecovery\StageRecovery.dll
```

Yup you were right, just a missed drag and drop. Sorry for bothering you.
