### ISSUE TITLE
KSP Stability and Performance issue

### ISSUE THREAD

**Issue by ProwlerProwl** [magico13/StageRecovery#49]
Hi, 

I have detected the following error while using Stage Recovery on my modded KSP. I have added and removed SR and the issue seems to go away with uninstalling SR. The error makes transitions from Flight into VAB or SPH freeze or take much longer than usual to load. Alt-F12 shows

[ERR 00:40:32.005] StageRecovery: No parent part found

[ERR 00:40:32.018] StageRecovery: No parent part found

[ERR 00:40:32.030] StageRecovery: No parent part found

spammed

The usual time of transition is less than 5 seconds usually.  With SR loaded it takes more than 10 minutes to load. Please help me capture whatever data you need to resolve this lagging and freezing issue.

Best regards,

**Comment by ProwlerProwl** [comment]
Found the root of the issue to be Mod Basic Delta V to cause null exception errors that made Stage Recovery unstable and caused it to slow down to a halt. Resolved by removing Basic Delta V. Issue seems to go away. I will keep testing and post back if I find something else.

**Comment by ProwlerProwl** [comment]
The same issue is back with spamming of:

[ERR 00:40:32.005] StageRecovery: No parent part found
[ERR 00:40:32.018] StageRecovery: No parent part found
[ERR 00:40:32.030] StageRecovery: No parent part found

Game performance drops to a halting non playable state, please help.

**Comment by magico13** [comment]
I hate to be that guy but @linuxgurugamer is maintaining this now over at https://github.com/linuxgurugamer/StageRecovery so you'll likely want to reopen this over there.

**Comment by ProwlerProwl** [comment]
Thank you, much. Have a great day.
